export const offersData = [
  {
    offerID: "1",
    positionName: "Senior Accountant",
    location: {
      country: "Polska",
      city: "Kraków",
      voivodeship: "małopolskie",
      street: "ul.Kowala 19",
    },
    salary: 45,
    salary: {
      value: 45,
      currency: "pln",
      payTime: "h",
    },
    startDate: "2022-05-12",
    endDate: "2022-08-14",
    employerID: "Brandex-1212341",
    employerName: "Brandex ",
    info: {
      handicap: "fiz, stopień umiarkowany",
      education: "Wykształcenie wyższe",
      pcSkill: "w stopniu podstawowym",
      physical: "Umiarkowane natężenie",
      experience: "Początkujący",
      shifts: "Tryb mieszany",
      commuting: "We własnym zakresie",
      workTime: "Pełny etat",
      start: "2022-05-12",
      leave: "Urlop płatny",
      workplace: "Praca zdalna",
      contract: "Umowa o pracę",
    },
    description: "opis",
    tasks: [
      "Wykonywanie poleceń szefa",
      "Parzenie kawy w firmowej kuchni",
      "Testowanie oprogramowania dla estońskiego klienta",
      "Tworzenie dokumentacji z użyciem pakietu Microsoft",
    ],
    requirements: [
      "Obsługa pakietu Microsoft w stopniu podstawowym",
      "Podstawy programowania w dowolnym języku obiektowym",
      "Komunikatywność i umiejętność pracy w zespole",
      "Umiejętność analitycznego myślenia",
      "Chęć do pracy i entuzjazm",
    ],
    benefits: [
      "Prywatna opieka medyczna",
      "Ubezpieczenie na życie",
      "Karta multisport",
      "Inicjatywy charytatywne i społeczne",
      "No dress code",
      "Karta zniżkowa na posiłki",
      "Parking dla pracowników",
    ],
    jobAppState: "W toku",
  },
];
