export const offersData = [
  {
    positionName: "Senior Accountant",
    location: {
      country: "Polska",
      city: "Kraków",
      voivodeship: "małopolskie",
      street: "ul.Kowala 19",
    },
    salary: {
      value: [40, 45],
      currency: "pln",
      payTime: "h",
    },
    tags: ["praca zdalna", "pełny etat"],
    expirationDate: "2022-06-12",
    startDate: "2022-05-12",
    employerID: "Brandex-1212341",
    employerName: "Brandex",
    tasks: [
      "Wykonywanie poleceń szefa",
      "Parzenie kawy w firmowej kuchni",
      "Testowanie oprogramowania dla estońskiego klienta",
      "Tworzenie dokumentacji z użyciem pakietu Microsoft",
    ],
    requirements: [
      "Obsługa pakietu Microsoft w stopniu podstawowym",
      "Podstawy programowania w dowolnym języku obiektowym",
      "Komunikatywność i umiejętność pracy w zespole",
      "Umiejętność analitycznego myślenia",
      "Chęć do pracy i entuzjazm",
    ],
    description: `Tester oprogramowania to odpowiedzialna rola, która jest niezbędna dla każdego software house'u jakim jest Brandex.
    Lorem Ipsum has been the industry's standard dummy text ever since the
    1500s, when an unknown printer took a galley of type and scrambled it to
    make ally type specimen book. It has survived not only five centuries,
    but also the leap into electronic typesetting, remaining essentia  took a galley of type and scrambled it to
    make ally type specimen book. It has survived not only five centuries,
    but also the leap into electronic typesetting, remaining essenti`,
    benefits: [
      "Prywatna opieka medyczna",
      "Ubezpieczenie na życie",
      "Karta multisport",
      "Inicjatywy charytatywne i społeczne",
      "No dress code",
      "Karta zniżkowa na posiłki",
      "Parking dla pracowników",
    ],
    contract: "UOP",
    info: {
      handicap: "fiz, stopień umiarkowany",
      education: "Wykształcenie wyższe",
      pcSkill: "w stopniu podstawowym",
      physical: "Umiarkowane natężenie",
      experience: "Początkujący",
      shifts: "Tryb mieszany",
      commuting: "We własnym zakresie",
      workTime: "Pełny etat",
    },
  },
  {
    positionName: "Lektor języka francuskiego",
    location: {
      country: "Polska",
      city: "Kraków",
      voivodeship: "małopolskie",
      street: "ul.Kowala 19",
    },
    salary: {
      value: [30, 32],
      currency: "pln",
      payTime: "h",
    },
    tags: ["praca hybrydowa", "pełny etat"],
    expirationDate: "2022-06-12",
    startDate: "2022-04-22",
    employerID: "Brandex-1212341",
    employerName: "Travel agent",
    tasks: [
      "Wykonywanie poleceń szefa",
      "Parzenie kawy w firmowej kuchni",
      "Testowanie oprogramowania dla estońskiego klienta",
      "Tworzenie dokumentacji z użyciem pakietu Microsoft",
    ],
    requirements: [
      "Obsługa pakietu Microsoft w stopniu podstawowym",
      "Podstawy programowania w dowolnym języku obiektowym",
      "Komunikatywność i umiejętność pracy w zespole",
      "Umiejętność analitycznego myślenia",
      "Chęć do pracy i entuzjazm",
    ],
    description: `Tester oprogramowania to odpowiedzialna rola, która jest niezbędna dla każdego software house'u jakim jest Brandex.
    Lorem Ipsum has been the industry's standard dummy text ever since the
    1500s, when an unknown printer took a galley of type and scrambled it to
    make ally type specimen book. It has survived not only five centuries,
    but also the leap into electronic typesetting, remaining essentia  took a galley of type and scrambled it to
    make ally type specimen book. It has survived not only five centuries,
    but also the leap into electronic typesetting, remaining essenti`,
    benefits: [
      "Prywatna opieka medyczna",
      "Ubezpieczenie na życie",
      "Karta multisport",
      "Inicjatywy charytatywne i społeczne",
      "No dress code",
      "Karta zniżkowa na posiłki",
      "Parking dla pracowników",
    ],
    contract: "UOP",
    info: {
      handicap: "fiz, stopień lekki",
      education: "Wykształcenie wyższe",
      pcSkill: "w stopniu podstawowym",
      physical: "Umiarkowane natężenie",
      experience: "Początkujący",
      shifts: "Tryb dzienny",
      commuting: "Praca zdalna",
      workTime: "Pełny etat",
    },
  },
  {
    positionName: "Senior Java Developer",
    location: {
      country: "Polska",
      city: "Kraków",
      voivodeship: "małopolskie",
      street: "ul.Kowala 19",
    },
    salary: {
      value: [30, 32],
      currency: "pln",
      payTime: "h",
    },
    tags: ["praca zdalna", "pełny etat"],
    expirationDate: "2022-06-12",
    startDate: "2022-04-22",
    employerID: "Brandex-1212341",
    employerName: "Brandex",
    tasks: [
      "Wykonywanie poleceń szefa",
      "Parzenie kawy w firmowej kuchni",
      "Testowanie oprogramowania dla estońskiego klienta",
      "Tworzenie dokumentacji z użyciem pakietu Microsoft",
    ],
    requirements: [
      "Obsługa pakietu Microsoft w stopniu podstawowym",
      "Podstawy programowania w dowolnym języku obiektowym",
      "Komunikatywność i umiejętność pracy w zespole",
      "Umiejętność analitycznego myślenia",
      "Chęć do pracy i entuzjazm",
    ],
    description: `Tester oprogramowania to odpowiedzialna rola, która jest niezbędna dla każdego software house'u jakim jest Brandex.
    Lorem Ipsum has been the industry's standard dummy text ever since the
    1500s, when an unknown printer took a galley of type and scrambled it to
    make ally type specimen book. It has survived not only five centuries,
    but also the leap into electronic typesetting, remaining essentia  took a galley of type and scrambled it to
    make ally type specimen book. It has survived not only five centuries,
    but also the leap into electronic typesetting, remaining essenti`,
    benefits: [
      "Prywatna opieka medyczna",
      "Ubezpieczenie na życie",
      "Karta multisport",
      "Inicjatywy charytatywne i społeczne",
      "No dress code",
      "Karta zniżkowa na posiłki",
      "Parking dla pracowników",
    ],
    contract: "UOP",
    info: {
      handicap: "fiz, stopień lekki",
      education: "Wykształcenie wyższe",
      pcSkill: "w stopniu podstawowym",
      physical: "Umiarkowane natężenie",
      experience: "Początkujący",
      shifts: "Tryb dzienny",
      commuting: "Praca zdalna",
      workTime: "Pełny etat",
    },
  },
  {
    positionName: "Lektor języka francuskiego",
    location: {
      country: "Polska",
      city: "Kraków",
      voivodeship: "małopolskie",
      street: "ul.Kowala 19",
    },
    salary: {
      value: [30, 32],
      currency: "pln",
      payTime: "h",
    },
    tags: ["praca zdalna", "pełny etat"],
    expirationDate: "2022-06-12",
    startDate: "2022-04-22",
    employerID: "Brandex-1212341",
    employerName: "Brandex",
    tasks: [
      "Wykonywanie poleceń szefa",
      "Parzenie kawy w firmowej kuchni",
      "Testowanie oprogramowania dla estońskiego klienta",
      "Tworzenie dokumentacji z użyciem pakietu Microsoft",
    ],
    requirements: [
      "Obsługa pakietu Microsoft w stopniu podstawowym",
      "Podstawy programowania w dowolnym języku obiektowym",
      "Komunikatywność i umiejętność pracy w zespole",
      "Umiejętność analitycznego myślenia",
      "Chęć do pracy i entuzjazm",
    ],
    description: `Tester oprogramowania to odpowiedzialna rola, która jest niezbędna dla każdego software house'u jakim jest Brandex.
    Lorem Ipsum has been the industry's standard dummy text ever since the
    1500s, when an unknown printer took a galley of type and scrambled it to
    make ally type specimen book. It has survived not only five centuries,
    but also the leap into electronic typesetting, remaining essentia  took a galley of type and scrambled it to
    make ally type specimen book. It has survived not only five centuries,
    but also the leap into electronic typesetting, remaining essenti`,
    benefits: [
      "Prywatna opieka medyczna",
      "Ubezpieczenie na życie",
      "Karta multisport",
      "Inicjatywy charytatywne i społeczne",
      "No dress code",
      "Karta zniżkowa na posiłki",
      "Parking dla pracowników",
    ],
    contract: "UOP",
    info: {
      handicap: "fiz, stopień lekki",
      education: "Wykształcenie wyższe",
      pcSkill: "w stopniu podstawowym",
      physical: "Umiarkowane natężenie",
      experience: "Początkujący",
      shifts: "Tryb dzienny",
      commuting: "Praca zdalna",
      workTime: "Pełny etat",
    },
  },
  {
    positionName: "Lektor języka francuskiego",
    location: {
      country: "Polska",
      city: "Kraków",
      voivodeship: "małopolskie",
      street: "ul.Kowala 19",
    },
    salary: {
      value: [30, 32],
      currency: "pln",
      payTime: "h",
    },
    tags: ["praca zdalna", "pełny etat"],
    expirationDate: "2022-06-12",
    startDate: "2022-04-22",
    employerID: "Brandex-1212341",
    employerName: "Brandex",
    tasks: [
      "Wykonywanie poleceń szefa",
      "Parzenie kawy w firmowej kuchni",
      "Testowanie oprogramowania dla estońskiego klienta",
      "Tworzenie dokumentacji z użyciem pakietu Microsoft",
    ],
    requirements: [
      "Obsługa pakietu Microsoft w stopniu podstawowym",
      "Podstawy programowania w dowolnym języku obiektowym",
      "Komunikatywność i umiejętność pracy w zespole",
      "Umiejętność analitycznego myślenia",
      "Chęć do pracy i entuzjazm",
    ],
    description: `Tester oprogramowania to odpowiedzialna rola, która jest niezbędna dla każdego software house'u jakim jest Brandex.
    Lorem Ipsum has been the industry's standard dummy text ever since the
    1500s, when an unknown printer took a galley of type and scrambled it to
    make ally type specimen book. It has survived not only five centuries,
    but also the leap into electronic typesetting, remaining essentia  took a galley of type and scrambled it to
    make ally type specimen book. It has survived not only five centuries,
    but also the leap into electronic typesetting, remaining essenti`,
    benefits: [
      "Prywatna opieka medyczna",
      "Ubezpieczenie na życie",
      "Karta multisport",
      "Inicjatywy charytatywne i społeczne",
      "No dress code",
      "Karta zniżkowa na posiłki",
      "Parking dla pracowników",
    ],
    contract: "UOP",
    info: {
      handicap: "fiz, stopień lekki",
      education: "Wykształcenie wyższe",
      pcSkill: "w stopniu podstawowym",
      physical: "Umiarkowane natężenie",
      experience: "Początkujący",
      shifts: "Tryb dzienny",
      commuting: "Praca zdalna",
      workTime: "Pełny etat",
    },
  },
];
